import { NextRequest, NextResponse } from "next/server";
import crypto from "node:crypto";
import { eq } from "drizzle-orm";
import { clerkClient } from "@clerk/nextjs/server";
import { getDb } from "@/lib/db";
import { subscriptions } from "@/lib/schema";
import { getResend } from "@/lib/resend";
import { brandedEmail } from "@/lib/email-template";
import { baseSubscriptionPlan, clearCommercialPlanEntitlement, setCommercialPlanEntitlement } from "@/lib/plan-entitlements";
import { isPaidPlan, planLabel, type BillingPeriod, type PaidPlan } from "@/lib/plans";

type PaddleEvent={event_id?:string;event_type:string;data:{id?:string;customer_id?:string;subscription_id?:string;custom_data?:{clerkUserId?:string;customerEmail?:string;tier?:string;billing?:BillingPeriod};current_billing_period?:{ends_at?:string};billing_period?:{ends_at?:string}}};
function verify(raw:string,header:string,secret:string){const parts=header.split(";").map(p=>p.trim().split("="));const ts=parts.find(([k])=>k==="ts")?.[1];const sigs=parts.filter(([k])=>k==="h1").map(([,v])=>v).filter(Boolean);if(!ts||!sigs.length)return false;const expected=crypto.createHmac("sha256",secret).update(`${ts}:${raw}`).digest("hex");const eb=Buffer.from(expected,"utf8");return sigs.some(s=>{const b=Buffer.from(s,"utf8");return b.length===eb.length&&crypto.timingSafeEqual(eb,b);});}
function addPeriod(from:Date,billing:BillingPeriod){const d=new Date(from);if(billing==="yearly")d.setUTCFullYear(d.getUTCFullYear()+1);else d.setUTCMonth(d.getUTCMonth()+1);return d;}
async function customerEmail(userId:string,supplied?:string){if(supplied)return supplied;try{const u=await(await clerkClient()).users.getUser(userId);return (u.emailAddresses.find(i=>i.id===u.primaryEmailAddressId)??u.emailAddresses[0])?.emailAddress;}catch{return undefined;}}
async function sendActivation(userId:string,tier:PaidPlan,supplied?:string){const email=await customerEmail(userId,supplied);if(!email)return;const result=await getResend().emails.send({from:process.env.RESEND_FROM??"onboarding@resend.dev",to:email,subject:"Vaš paket Slikaj Račun je aktiviran",html:brandedEmail({preheader:"Plačilo je uspešno in paket je aktiviran",eyebrow:"Uspešno plačilo",title:"Vaš paket je aktiviran",introHtml:`<p style="margin:0">Hvala za plačilo. Paket <strong>${planLabel(tier)}</strong> je aktiviran in ga lahko takoj uporabljate.</p>`,noticeHtml:"AI OCR limiti in funkcije paketa so že aktivni.",cta:{label:"Odpri Slikaj Račun",url:"https://www.posljiracun.si/scan"}})});if(result.error)console.error("[paddle webhook] activation email failed",result.error);}
async function activate(event:PaddleEvent){const custom=event.data.custom_data;const userId=custom?.clerkUserId;const tier=custom?.tier;if(!userId||!isPaidPlan(tier)){console.warn("[paddle webhook] invalid/missing commercial plan",{eventId:event.event_id,tier,hasUserId:Boolean(userId)});return;}const billing=custom?.billing??"monthly";const now=new Date();const explicit=event.data.current_billing_period?.ends_at??event.data.billing_period?.ends_at;const periodEnd=explicit?new Date(explicit):addPeriod(now,billing);const db=getDb();const[existing]=await db.select().from(subscriptions).where(eq(subscriptions.clerkUserId,userId)).limit(1);const wasActive=Boolean(existing?.currentPeriodEnd&&existing.currentPeriodEnd>now);const base=baseSubscriptionPlan(tier);await db.insert(subscriptions).values({clerkUserId:userId,plan:base,trialEndsAt:now,currentPeriodEnd:periodEnd,paddleCustomerId:event.data.customer_id??null,paddleSubscriptionId:event.data.subscription_id??event.data.id??null,updatedAt:now}).onConflictDoUpdate({target:subscriptions.clerkUserId,set:{plan:base,currentPeriodEnd:periodEnd,paddleCustomerId:event.data.customer_id??existing?.paddleCustomerId??null,paddleSubscriptionId:event.data.subscription_id??event.data.id??existing?.paddleSubscriptionId??null,updatedAt:now}});await setCommercialPlanEntitlement({clerkUserId:userId,plan:tier,billing,source:"paddle"});console.info("[paddle webhook] commercial plan activated",{userId,tier,billing,periodEnd:periodEnd.toISOString()});if(!wasActive)await sendActivation(userId,tier,custom?.customerEmail).catch(e=>console.error("activation email",e));}
export async function POST(req:NextRequest){const secret=process.env.PADDLE_WEBHOOK_SECRET;if(!secret)return NextResponse.json({error:"Webhook is not configured"},{status:500});const sig=req.headers.get("paddle-signature");if(!sig)return NextResponse.json({error:"Missing signature"},{status:400});const raw=await req.text();if(!verify(raw,sig,secret))return NextResponse.json({error:"Invalid signature"},{status:401});let event:PaddleEvent;try{event=JSON.parse(raw);}catch{return NextResponse.json({error:"Invalid JSON"},{status:400});}switch(event.event_type){case"transaction.completed":case"subscription.created":case"subscription.activated":case"subscription.resumed":case"subscription.updated":await activate(event);break;case"subscription.canceled":{const userId=event.data.custom_data?.clerkUserId;if(userId){await getDb().update(subscriptions).set({plan:"canceled",updatedAt:new Date()}).where(eq(subscriptions.clerkUserId,userId));await clearCommercialPlanEntitlement(userId);}}break;}return NextResponse.json({received:true});}
