import { NextRequest, NextResponse } from "next/server";
import { auth } from "@clerk/nextjs/server";
import { and,eq } from "drizzle-orm";
import { z } from "zod";
import { getDb } from "@/lib/db";
import { companies } from "@/lib/schema";
import { getCompanyDeliverySettings,saveCompanyDeliverySettings } from "@/lib/invoice-intelligence/delivery-settings";
import { getStatus } from "@/lib/subscription";
import { getPlanConfig } from "@/lib/plans";
const schema=z.object({mode:z.enum(["email_ocr","api_json","xml_email"]),apiEndpoint:z.string().max(2048).nullable().optional(),apiBearerToken:z.string().max(4096).nullable().optional(),clearApiToken:z.boolean().optional(),xmlFormat:z.enum(["ubl_2_1","eslog_2_0_original"]).optional()});
async function ownedCompany(id:number,userId:string){const[c]=await getDb().select({id:companies.id,name:companies.name,recipientEmail:companies.recipientEmail}).from(companies).where(and(eq(companies.id,id),eq(companies.clerkUserId,userId))).limit(1);return c;}
export async function GET(_req:NextRequest,{params}:{params:Promise<{id:string}>}){const{userId}=await auth();if(!userId)return NextResponse.json({error:"Unauthorized"},{status:401});const id=Number((await params).id);if(!Number.isInteger(id))return NextResponse.json({error:"Invalid company id"},{status:400});const company=await ownedCompany(id,userId);if(!company)return NextResponse.json({error:"Not found"},{status:404});const [delivery,status]=await Promise.all([getCompanyDeliverySettings(id,userId),getStatus(userId)]);const cfg=getPlanConfig(status.commercialPlan);return NextResponse.json({company,delivery,entitlement:{plan:status.commercialPlan,structuredDelivery:cfg.structuredDelivery,apiDelivery:cfg.apiDelivery}},{headers:{"Cache-Control":"no-store"}});}
export async function PUT(req:NextRequest,{params}:{params:Promise<{id:string}>}){const{userId}=await auth();if(!userId)return NextResponse.json({error:"Unauthorized"},{status:401});const id=Number((await params).id);if(!Number.isInteger(id))return NextResponse.json({error:"Invalid company id"},{status:400});const company=await ownedCompany(id,userId);if(!company)return NextResponse.json({error:"Not found"},{status:404});try{const data=schema.parse(await req.json());const status=await getStatus(userId);const cfg=getPlanConfig(status.commercialPlan);if(data.mode==="xml_email"&&!cfg.structuredDelivery)return NextResponse.json({error:"XML/eSLOG pošiljanje ni vključeno v vaš paket.",code:"feature_not_in_plan",upgradeUrl:"/cenik"},{status:403});if(data.mode==="api_json"&&!cfg.apiDelivery)return NextResponse.json({error:"JSON API pošiljanje ni vključeno v vaš paket.",code:"feature_not_in_plan",upgradeUrl:"/cenik"},{status:403});const delivery=await saveCompanyDeliverySettings({companyId:id,clerkUserId:userId,...data});return NextResponse.json({company,delivery},{headers:{"Cache-Control":"no-store"}});}catch(error){return NextResponse.json({error:error instanceof z.ZodError?"Invalid delivery settings":error instanceof Error?error.message:"Could not save delivery settings"},{status:400});}}
