import { NextRequest, NextResponse } from "next/server";
import { auth } from "@clerk/nextjs/server";
import { getDb } from "@/lib/db";
import { invoices, userSettings, companies } from "@/lib/schema";
import { sendInvoiceEmail } from "@/lib/resend";
import { FREE_MONTHLY_LIMIT, getStatus } from "@/lib/subscription";
import { getPlanConfig } from "@/lib/plans";
import { eq, and } from "drizzle-orm";
import { z } from "zod";
import { enqueueInvoiceDocument } from "@/lib/invoice-intelligence/queue";
import { OcrCommercialQuotaError } from "@/lib/invoice-intelligence/quota";
import { getCompanyDeliverySettings } from "@/lib/invoice-intelligence/delivery-settings";
import type { DeliveryMode } from "@/lib/invoice-intelligence/delivery-format";

const MAX_FILE_BYTES=10*1024*1024; const ALLOWED_MIME=new Set(["application/pdf","image/jpeg","image/png","image/webp","image/heic","image/heif","application/xml","text/xml"]);
const schema=z.object({subject:z.string().min(1).max(255).default("Račun"),imageBase64:z.string().min(1).max(14*1024*1024),filename:z.string().min(1).max(255),mime:z.string().max(96).default("image/jpeg"),companyId:z.number().int().positive().optional(),messageBody:z.string().max(2000).optional()});

export async function POST(req:NextRequest){const{userId}=await auth();if(!userId)return NextResponse.json({error:"Unauthorized"},{status:401});const status=await getStatus(userId);const cfg=getPlanConfig(status.commercialPlan);if(!status.canSend)return NextResponse.json({success:false,error:"Paket ni aktiven. Nadgradite paket za nadaljevanje.",code:"subscription_required",plan:status.commercialPlan},{status:402});if(status.isFree&&status.monthlyUsage>=FREE_MONTHLY_LIMIT)return NextResponse.json({success:false,error:"Dosežena je mesečna omejitev 3 računov na brezplačnem paketu.",code:"free_limit_reached"},{status:403});
try{const data=schema.parse(await req.json());const bytes=Buffer.from(data.imageBase64,"base64");if(bytes.length===0||bytes.length>MAX_FILE_BYTES)return NextResponse.json({success:false,error:"Neveljavna datoteka ali datoteka večja od 10 MB."},{status:400});if(!ALLOWED_MIME.has(data.mime))return NextResponse.json({success:false,error:"Nepodprt tip datoteke."},{status:415});if(data.mime==="application/pdf"&&bytes.subarray(0,4).toString()!=="%PDF")return NextResponse.json({success:false,error:"Neveljaven PDF."},{status:400});
const db=getDb();let recipientEmail:string|null|undefined;let deliveryMode:DeliveryMode="email_ocr";if(data.companyId){const[company]=await db.select().from(companies).where(and(eq(companies.id,data.companyId),eq(companies.clerkUserId,userId))).limit(1);recipientEmail=company?.recipientEmail;if(company)deliveryMode=(await getCompanyDeliverySettings(company.id,userId)).mode;}else{const[settings]=await db.select().from(userSettings).where(eq(userSettings.clerkUserId,userId)).limit(1);recipientEmail=settings?.recipientEmail;}if(!recipientEmail)return NextResponse.json({success:false,error:"V Nastavitvah določite prejemni e-mail.",code:"no_recipient"},{status:422});
if(deliveryMode==="xml_email"&&!cfg.structuredDelivery)return NextResponse.json({success:false,error:"XML/eSLOG pošiljanje ni vključeno v vaš paket.",code:"feature_not_in_plan",upgradeUrl:"/cenik"},{status:403});if(deliveryMode==="api_json"&&!cfg.apiDelivery)return NextResponse.json({success:false,error:"JSON API pošiljanje ni vključeno v vaš paket.",code:"feature_not_in_plan",upgradeUrl:"/cenik"},{status:403});
const filename=sanitizeFilename(data.filename);const[result]=await db.insert(invoices).values({clerkUserId:userId,recipientEmail,companyId:data.companyId??null,subject:data.subject,imageData:data.imageBase64,imageMime:data.mime,filename,status:"pending"}).returning({id:invoices.id});let processingDocumentId:number|null=null;let queueErrorMessage:string|null=null;let quotaError:OcrCommercialQuotaError|null=null;try{processingDocumentId=await enqueueInvoiceDocument({clerkUserId:userId,companyId:data.companyId??null,sourceInvoiceId:result.id,filename,mimeType:data.mime,base64:data.imageBase64});}catch(error){queueErrorMessage=error instanceof Error?error.message:"unknown";if(error instanceof OcrCommercialQuotaError)quotaError=error;console.error("invoice_reader_enqueue_failed",queueErrorMessage);}
if(deliveryMode!=="email_ocr"){if(!processingDocumentId){await db.update(invoices).set({status:"failed",errorMessage:`Structured delivery could not be queued: ${queueErrorMessage||"unknown error"}`}).where(eq(invoices.id,result.id));if(quotaError)return NextResponse.json({success:false,error:quotaError.message,code:quotaError.code,quotaType:quotaError.quotaType,plan:quotaError.plan,upgradeUrl:"/cenik"},{status:402});return NextResponse.json({success:false,error:"Strukturirane obdelave ni bilo mogoče uvrstiti v čakalno vrsto."},{status:500});}return NextResponse.json({success:true,id:result.id,processingDocumentId,deliveryMode,queuedForStructuredDelivery:true});}
try{await sendInvoiceEmail({to:recipientEmail,subject:data.subject,imageBase64:data.imageBase64,filename,mime:data.mime,messageBody:data.messageBody});await db.update(invoices).set({status:"sent",sentAt:new Date()}).where(eq(invoices.id,result.id));return NextResponse.json({success:true,id:result.id,processingDocumentId,deliveryMode,ocrQueued:Boolean(processingDocumentId),ocrLimitReached:Boolean(quotaError),ocrMessage:quotaError?.message??null,ocrPlan:quotaError?.plan??null});}catch(emailErr){const msg=emailErr instanceof Error?emailErr.message:String(emailErr);await db.update(invoices).set({status:"failed",errorMessage:msg}).where(eq(invoices.id,result.id));return NextResponse.json({success:false,error:msg,processingDocumentId,deliveryMode},{status:500});}}
catch(err){return NextResponse.json({success:false,error:err instanceof Error?err.message:"Napaka"},{status:400});}}
function sanitizeFilename(filename:string){const base=filename.split(/[\\/]/).pop()||"invoice";return base.replace(/[\u0000-\u001f\u007f]/g,"").replace(/[^a-zA-Z0-9._()\- čšžćđČŠŽĆĐ]/g,"_").slice(0,255);}
