import { clerkClient } from "@clerk/nextjs/server";
import { neon } from "@neondatabase/serverless";
import { ADMIN_OCR_OVERRIDE, getPlanConfig, planLabel, type CommercialPlan } from "@/lib/plans";
import { getCommercialPlanCode } from "@/lib/plan-entitlements";

export type OcrQuotaEntitlement = { plan: CommercialPlan; planName: string; monthlyDocumentLimit: number; monthlyPageLimit: number; dailyPageLimit: number; adminOverride: boolean };
export type OcrUsageSummary = OcrQuotaEntitlement & { monthDocuments: number; monthPages: number; dayPages: number; estimatedMonthCostMicros: number; documentPercent: number; pagePercent: number; usagePercent: number; warningLevel: "ok"|"warning"|"critical"|"blocked"; remainingDocuments: number; remainingPages: number; noticeSl: string|null; noticeEn: string|null };
export class OcrCommercialQuotaError extends Error { readonly code = "ocr_plan_limit_reached"; readonly retryable = false; constructor(message: string, readonly quotaType: "documents"|"pages"|"daily_pages", readonly limit: number, readonly plan: CommercialPlan) { super(message); this.name = "OcrCommercialQuotaError"; } }

const emailCache = new Map<string,{email:string|null;expiresAt:number}>();
function sqlClient(){const url=process.env.DATABASE_URL;if(!url)throw new Error("DATABASE_URL is not set");return neon(url);}
async function resolvePrimaryEmail(clerkUserId:string){const cached=emailCache.get(clerkUserId);if(cached&&cached.expiresAt>Date.now())return cached.email;let email:string|null=null;try{const user=await(await clerkClient()).users.getUser(clerkUserId);const primary=user.emailAddresses.find(i=>i.id===user.primaryEmailAddressId)??user.emailAddresses[0];email=primary?.emailAddress?.toLowerCase()??null;}catch(error){console.warn("ocr_quota_email_lookup_failed",{clerkUserId,error});}emailCache.set(clerkUserId,{email,expiresAt:Date.now()+600000});return email;}

export async function resolveOcrEntitlement(clerkUserId:string):Promise<OcrQuotaEntitlement>{const[plan,email]=await Promise.all([getCommercialPlanCode(clerkUserId),resolvePrimaryEmail(clerkUserId)]);if(email===ADMIN_OCR_OVERRIDE.email){return{plan,planName:`${planLabel(plan)} · Admin`,monthlyDocumentLimit:ADMIN_OCR_OVERRIDE.monthlyDocuments,monthlyPageLimit:ADMIN_OCR_OVERRIDE.monthlyPages,dailyPageLimit:ADMIN_OCR_OVERRIDE.dailyPages,adminOverride:true};}const cfg=getPlanConfig(plan);return{plan,planName:cfg.nameSl,monthlyDocumentLimit:cfg.ocrDocumentsMonthly,monthlyPageLimit:cfg.ocrPagesMonthly,dailyPageLimit:cfg.ocrPagesMonthly,adminOverride:false};}

export async function getOcrUsageSummary(clerkUserId:string):Promise<OcrUsageSummary>{const entitlement=await resolveOcrEntitlement(clerkUserId);const sql=sqlClient();const now=new Date();const dayStart=new Date(Date.UTC(now.getUTCFullYear(),now.getUTCMonth(),now.getUTCDate()));const monthStart=new Date(Date.UTC(now.getUTCFullYear(),now.getUTCMonth(),1));const scope=`user:${clerkUserId}`;const[docRows,bucketRows]=await Promise.all([sql`SELECT count(*)::int AS "count" FROM "invoiceDocuments" WHERE "clerkUserId"=${clerkUserId} AND "createdAt">=${monthStart}`,sql`SELECT "bucketType","bucketStart","reservedPages","estimatedCostMicros" FROM "invoiceOcrUsageBuckets" WHERE "scopeKey"=${scope} AND (("bucketType"='day' AND "bucketStart"=${dayStart}) OR ("bucketType"='month' AND "bucketStart"=${monthStart}))`]);const monthDocuments=Number(docRows[0]?.count??0);const day=bucketRows.find(r=>r.bucketType==="day");const month=bucketRows.find(r=>r.bucketType==="month");const dayPages=Number(day?.reservedPages??0);const monthPages=Number(month?.reservedPages??0);const estimatedMonthCostMicros=Number(month?.estimatedCostMicros??0);const documentPercent=percent(monthDocuments,entitlement.monthlyDocumentLimit);const pagePercent=percent(monthPages,entitlement.monthlyPageLimit);const usagePercent=Math.max(documentPercent,pagePercent);const warningLevel=usagePercent>=100?"blocked":usagePercent>=95?"critical":usagePercent>=80?"warning":"ok";const remainingDocuments=Math.max(0,entitlement.monthlyDocumentLimit-monthDocuments);const remainingPages=Math.max(0,entitlement.monthlyPageLimit-monthPages);const notices=buildNotice(entitlement,{monthDocuments,monthPages,dayPages,warningLevel});return{...entitlement,monthDocuments,monthPages,dayPages,estimatedMonthCostMicros,documentPercent,pagePercent,usagePercent,warningLevel,remainingDocuments,remainingPages,...notices};}

export async function assertOcrDocumentQuota(clerkUserId:string){const s=await getOcrUsageSummary(clerkUserId);if(s.monthDocuments>=s.monthlyDocumentLimit)throw new OcrCommercialQuotaError(s.adminOverride?`Admin OCR mesečni limit ${s.monthlyDocumentLimit} dokumentov je dosežen.`:`Dosežen je mesečni OCR limit paketa ${s.planName}: ${s.monthlyDocumentLimit} dokumentov. Originalno pošiljanje računov še vedno deluje; za nadaljnjo AI obdelavo nadgradite paket.`,"documents",s.monthlyDocumentLimit,s.plan);return s;}
export function quotaPageError(e:OcrQuotaEntitlement,type:"pages"|"daily_pages"){const limit=type==="daily_pages"?e.dailyPageLimit:e.monthlyPageLimit;return new OcrCommercialQuotaError(e.adminOverride?`Admin OCR ${type==="daily_pages"?"dnevni":"mesečni"} limit ${limit} strani je dosežen.`:`Dosežen je ${type==="daily_pages"?"dnevni":"mesečni"} OCR limit paketa ${e.planName}: ${limit} strani. Originalno pošiljanje računov še vedno deluje; za nadaljnjo AI obdelavo nadgradite paket.`,type,limit,e.plan);}
function percent(v:number,l:number){if(l<=0)return v>0?100:0;return Math.min(100,Math.round(v/l*1000)/10);}
function buildNotice(e:OcrQuotaEntitlement,u:{monthDocuments:number;monthPages:number;dayPages:number;warningLevel:OcrUsageSummary["warningLevel"]}){if(e.adminOverride&&u.dayPages>=e.dailyPageLimit)return{noticeSl:`Dosežen je admin dnevni OCR limit ${e.dailyPageLimit} strani. OCR obdelava je ustavljena do naslednjega dne.`,noticeEn:`The admin daily OCR limit of ${e.dailyPageLimit} pages has been reached. OCR processing is paused until the next day.`};if(u.warningLevel==="blocked")return{noticeSl:`Dosežen je OCR limit paketa ${e.planName}. Poraba: ${u.monthDocuments}/${e.monthlyDocumentLimit} dokumentov in ${u.monthPages}/${e.monthlyPageLimit} strani.`,noticeEn:`The OCR limit for ${e.planName} has been reached. Usage: ${u.monthDocuments}/${e.monthlyDocumentLimit} documents and ${u.monthPages}/${e.monthlyPageLimit} pages.`};if(u.warningLevel==="critical")return{noticeSl:`Porabili ste najmanj 95 % mesečnega OCR limita paketa ${e.planName}.`,noticeEn:`You have used at least 95% of the monthly OCR allowance for ${e.planName}.`};if(u.warningLevel==="warning")return{noticeSl:`Porabili ste najmanj 80 % mesečnega OCR limita paketa ${e.planName}.`,noticeEn:`You have used at least 80% of the monthly OCR allowance for ${e.planName}.`};return{noticeSl:null,noticeEn:null};}
