import { NextRequest,NextResponse } from "next/server";
import { clerkClient } from "@clerk/nextjs/server";
import { z } from "zod";
import { getDb } from "@/lib/db";
import { subscriptions } from "@/lib/schema";
import { eq } from "drizzle-orm";
import { isCurrentUserAdmin } from "@/lib/admin";
import { getResend } from "@/lib/resend";
import { brandedEmail } from "@/lib/email-template";
import { baseSubscriptionPlan,setCommercialPlanEntitlement } from "@/lib/plan-entitlements";
import { planLabel,type PaidPlan } from "@/lib/plans";
const schema=z.object({email:z.string().trim().email().max(320).optional(),userId:z.string().trim().min(1).max(255).optional(),plan:z.enum(["basic","pro","accounting_pro","accounting_max"]),billing:z.enum(["monthly","yearly"])}).refine(d=>d.email||d.userId,{message:"E-pošta ali uporabnik je obvezen."});
function addPeriod(from:Date,billing:"monthly"|"yearly"){const d=new Date(from);if(billing==="yearly")d.setUTCFullYear(d.getUTCFullYear()+1);else d.setUTCMonth(d.getUTCMonth()+1);return d;}
export async function POST(req:NextRequest){if(!(await isCurrentUserAdmin()))return NextResponse.json({error:"Forbidden"},{status:403});try{const data=schema.parse(await req.json());const client=await clerkClient();const user=data.userId?await client.users.getUser(data.userId).catch(()=>null):(await client.users.getUserList({emailAddress:[data.email!],limit:10})).data.find(c=>c.emailAddresses.some(i=>i.emailAddress.toLowerCase()===data.email!.toLowerCase()));if(!user)return NextResponse.json({error:"Uporabnik s tem e-poštnim naslovom ni registriran."},{status:404});const email=(user.emailAddresses.find(i=>i.id===user.primaryEmailAddressId)??user.emailAddresses[0])?.emailAddress;if(!email)return NextResponse.json({error:"Uporabnik nima e-poštnega naslova."},{status:400});const now=new Date();const db=getDb();const[existing]=await db.select().from(subscriptions).where(eq(subscriptions.clerkUserId,user.id)).limit(1);const extensionBase=existing?.currentPeriodEnd&&existing.currentPeriodEnd>now?existing.currentPeriodEnd:now;const currentPeriodEnd=addPeriod(extensionBase,data.billing);const commercial=data.plan as PaidPlan;const base=baseSubscriptionPlan(commercial);await db.insert(subscriptions).values({clerkUserId:user.id,plan:base,trialEndsAt:now,currentPeriodEnd,updatedAt:now}).onConflictDoUpdate({target:subscriptions.clerkUserId,set:{plan:base,currentPeriodEnd,updatedAt:now}});await setCommercialPlanEntitlement({clerkUserId:user.id,plan:commercial,billing:data.billing,source:"admin"});const emailResult=await getResend().emails.send({from:process.env.RESEND_FROM??"onboarding@resend.dev",to:email,subject:"Vaš paket Slikaj Račun je aktiviran",html:brandedEmail({preheader:"Vaš paket Slikaj Račun je aktiviran",eyebrow:"Paket je pripravljen",title:"Paket je aktiviran",introHtml:`<p style="margin:0">Vaš paket <strong>${planLabel(commercial)}</strong> je aktiviran oziroma podaljšan do <strong>${currentPeriodEnd.toLocaleDateString("sl-SI")}</strong>.</p>`,noticeHtml:"Vse funkcije in OCR limiti izbranega paketa so aktivni.",cta:{label:"Odpri Slikaj Račun",url:"https://www.posljiracun.si/scan"}})});return NextResponse.json({success:true,expiresAt:currentPeriodEnd.toISOString(),plan:commercial,emailSent:!emailResult.error});}catch(error){console.error("[admin subscription activation]",error);return NextResponse.json({error:error instanceof z.ZodError?"Preverite vnesene podatke.":error instanceof Error?error.message:"Aktivacija ni uspela."},{status:400});}}
